config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :tasks do
  
  end
  resources :boards
  
  get '/agile_board' => 'home#agile_board' 
  post '/change_board' => 'home#change_board' 
  post '/tasks_create' => 'tasks#task_create' 
  post '/toogle_status_task/:id' => 'tasks#toogle_status_task' 
  get '/respond_add_task' => 'home#respond_add_task' 
  

  root 'home#agile_board'

end

app/models/board.rb
class Board < ActiveRecord::Base
      has_many :tasks
      belongs_to :user
      validates_presence_of :title
      validates_length_of :title, :minimum => 10
      validates_length_of :title, :maximum => 200

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 
  before_action :correct_user, only: [:edit, :update, :destroy]  
  
  
  # GET /boards
  # GET /boards.json
  def index
     @boards = current_user.boards.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
     @board = current_user.boards.build
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.build(board_params)
    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :public, :name)
    end
    
     # Vefify correct user 
    def correct_user
      @board = current_user.boards.find_by(id: params[:id])
      redirect_to boards_path, notice: "Not authorized to edit this board" if @board.nil?
    end
    
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
   <div class="form-group">
      <%= f.check_box :public %>
      <%= f.label :public, class: "text-muted i-checks"  %>
   </div>


  <%= f.submit locals[:action], class: "btn btn-primary" %>

<% end %>



<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });

});

</script>

<% end %>

app/views/boards/edit.html.erb
 <div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
    <div class="col-lg-6">
       <div class="panel panel-primary">
          <div class="panel-heading">
            <h2>Editing Board</h2>
          </div>
          <div class="panel-body">
             <%= render 'form', :locals => {:action => "Edit Board"} %>
          </div>
           <div class="panel-footer">
                <%= link_to 'Show', @board %> |
                <%= link_to 'Back', boards_path, class: "btn btn-sm btn-white" %>
            </div>
        </div>  
    </div>
</div>
</div>

app/views/boards/index.html.erb
 <div class="wrapper wrapper-content white-bg  animated fadeInRight">
   <div class="row">
    <div class="col-lg-12">
         <div class="ibox">
            <div class="ibox-title">
                <h2>My Boards</h2>
            </div>
            <% unless notice.blank? %>
                <div class="alert alert-success">
                    <p id="notice"><%= notice %></p>
                </div>
            <% end %>
            <div class="ibox-content">
                <table class="table">
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Public</th>
                        <th>User</th>
                        <th>Create At</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>
                  
                    <tbody>
                      <% @boards.each do |board| %>
                        <tr>
                          <td><%= board.title %></td>
                          <td><%= board.public %></td>
                          <th><%= board.user.name %></th>
                          <th><%= board.created_at.strftime("%F") + %{ - } + board.created_at.strftime("%T")  %></th>
                          <td><%= link_to 'Show', board, class: "btn btn-w-m btn-success" %></td>
                          <td><%= link_to 'Edit', edit_board_path(board), class: "btn btn-w-m btn-warning" %></td>
                          <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-w-m btn-danger" %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                  </br>
                    <%= link_to 'New Board', new_board_path, class: "btn btn-primary" %>
                    <div class="center">
                       <%= will_paginate @boards, renderer: BootstrapPagination::Rails %>
                     </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/boards/new.html.erb
 <div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
    <div class="col-lg-6">
       <div class="panel panel-primary">
          <div class="panel-heading">
            <h2>New Board</h2>
          </div>
          <div class="panel-body">
            <%= render 'form', :locals => {:action => "Add Board"} %>
          </div>
           <div class="panel-footer">
               <%= link_to 'Back', boards_path, class: "btn btn-sm btn-white" %>
            </div>
        </div>  
    </div>
</div>
</div>

app/views/boards/show.html.erb
 <div class="wrapper wrapper-content animated fadeInRight">
   <div class="row">
    <div class="col-lg-6">
       <div class="panel panel-primary">
          <div class="panel-heading">
            <h2> Board: <%= @board.title %> </h2>
          </div>
           <% unless notice.blank? %>
            <div class="alert alert-success">
                <p id="notice"><%= notice %></p>
            </div>
            <% end %>
          <div class="panel-body">
             <p>
              <strong>Title:</strong>
              <%= @board.title %>
            </p>
            
            <p>
              <strong>Public:</strong>
              <%= @board.public %>
            </p>
             <p>
              <strong>Create_at:</strong>
               <%= @board.created_at.strftime("%F") + %{ - } + @board.created_at.strftime("%T") %>
            </p>
          </div>
           <div class="panel-footer">
                <%= link_to 'Edit', edit_board_path(@board), class: "btn btn-primary" %> |
                <%= link_to 'Back', boards_path, class: "btn btn-sm btn-white" %>
            </div>
        </div>  
    </div>
</div>
</div>