config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users
  resources :tasks do
  
  end
  resources :boards
  
  get '/agile_board' => 'home#agile_board' 
  post '/change_board' => 'home#change_board' 
  post '/tasks_create' => 'tasks#task_create' 
  post '/toogle_status_task/:id' => 'tasks#toogle_status_task' 
  get '/respond_add_task' => 'home#respond_add_task' 
  

  root 'home#agile_board'

end

app/views/layouts/_agile_board.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>todorock</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="blue-bg">
  
  <%= render "layouts/header"%>
  
  <div class="container">
     <%= yield %>
 </div>



  <!-- Include javascript per-view -->
   <%= yield :javascript %>
</body>
 
</html>

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="pull-right">
       <strong>Copyright</strong> todorock &copy; 2016
    </div>
    <div>
        <h4></h4>  
    </div>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "todorock", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Agile Board", root_path %></li>
         <% if user_signed_in? %>
             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.name.titleize%>   <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Boards", boards_path %></li>
                <li><%= link_to "My Tasks", tasks_path %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li>
                    <%= link_to  destroy_user_session_path, method: :delete do %>
                        <i class="fa fa-sign-out"></i>Logout
                    <% end %>
                </li>
              </ul>
            </li>
         <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
           <li><%= link_to "Sign Up", new_user_registration_path %></li>
         <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>todorock</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "layouts/header"%>
  
  <div class="container">
     <%= yield %>
 </div>



  <!-- Include javascript per-view -->
   <%= yield :javascript %>
</body>
 
</html>